spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shop_assist"
    username: shop_assist
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

token:
  secretKey: "This is token secret key"