spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shop_assist"
    username: shop_assist
    password: 123456

jwt:
  secretKey: "This is token secret key"

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml