name: BackEnd CI

on:
  push:
    branches: [ "main" ]
    path: 
      - 'back-end/**'
  pull_request:
    branches: [ "main" ]
    path: 
      - 'back-end/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: helloWorld
      run: echo "hello world"